# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DerogSatellitePlugin
                                 A QGIS plugin
 Analyse terrain et téléchargement d'images satellites
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-13
        copyright            : (C) 2026 by medaf
        email                : medaf
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DerogSatellitePlugin class from file DerogSatellitePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .derog_satellite_plugin import DerogSatellitePlugin
    return DerogSatellitePlugin(iface)
