# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'derog_satellite_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DerogSatellitePluginDialogBase(object):
    def setupUi(self, DerogSatellitePluginDialogBase):
        DerogSatellitePluginDialogBase.setObjectName("DerogSatellitePluginDialogBase")
        DerogSatellitePluginDialogBase.resize(993, 564)
        DerogSatellitePluginDialogBase.setMinimumSize(QtCore.QSize(500, 400))
        self.button_box = QtWidgets.QDialogButtonBox(DerogSatellitePluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(DerogSatellitePluginDialogBase)
        self.label.setGeometry(QtCore.QRect(340, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.btnDerogation = QtWidgets.QPushButton(DerogSatellitePluginDialogBase)
        self.btnDerogation.setGeometry(QtCore.QRect(10, 40, 321, 71))
        self.btnDerogation.setObjectName("btnDerogation")
        self.btnSat = QtWidgets.QPushButton(DerogSatellitePluginDialogBase)
        self.btnSat.setGeometry(QtCore.QRect(660, 40, 321, 71))
        self.btnSat.setObjectName("btnSat")

        self.retranslateUi(DerogSatellitePluginDialogBase)
        self.button_box.accepted.connect(DerogSatellitePluginDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(DerogSatellitePluginDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DerogSatellitePluginDialogBase)

    def retranslateUi(self, DerogSatellitePluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DerogSatellitePluginDialogBase.setWindowTitle(_translate("DerogSatellitePluginDialogBase", "Derog&Satellite Plugin"))
        self.label.setText(_translate("DerogSatellitePluginDialogBase", "Plugin El Afia Mohamed"))
        self.btnDerogation.setText(_translate("DerogSatellitePluginDialogBase", "Derogation"))
        self.btnSat.setText(_translate("DerogSatellitePluginDialogBase", "Telechargement d\'une image salettite"))
